class window.Probability extends Backbone.Model

  initialize: ->
    @set 'recommend', "NOT SURE"
    # @on 'recommend', @onRecommend

  onRecommend: (playerHand, dealerHand)->
    console.log(playerHand, dealerHand)
    if playerHand <= 11 then @set 'recommend', "hit"
    else if playerHand >= 17 then @set 'recommend', "stand"
    else if playerHand <= 16 and dealerHand >= 7 then @set 'recommend', "hit"
    else if playerHand <= 13 and dealerHand < 7 then @set 'recommend', "stand"
    else if playerHand is 12 and (3 < dealerHand < 7) then @set 'recommend', "stand"
    else @set 'recommend', "hit"

# var checkProb = function(playerScore, dealerScore) {
#   var probabilities = {
#     2: {
#       3: true,
#       4: true,
#       5: true,
#       6: true,
#       7: true,
#       8: true,
#       9: true,
#       10: true,
#       11: true,
#       12: true,
#       13: false,
#       14: false,
#       15: false,
#       16: false,
#       17: false,
#       18: false,
#       19: false,
#       20: false,
#       21: false,
#     },
#     3: {
#       3: true,
#       4: true,
#       5: true,
#       6: true,
#       7: true,
#       8: true,
#       9: true,
#       10: true,
#       11: true,
#       12: true,
#       13: false,
#       14: false,
#       15: false,
#       16: false,
#       17: false,
#       18: false,
#       19: false,
#       20: false,
#       21: false,
#     },
#     4: {
#       3: true,
#       4: true,
#       5: true,
#       6: true,
#       7: true,
#       8: true,
#       9: true,
#       10: true,
#       11: true,
#       12: false,
#       13: false,
#       14: false,
#       15: false,
#       16: false,
#       17: false,
#       18: false,
#       19: false,
#       20: false,
#       21: false,
#     },
#     5: {
#       3: true,
#       4: true,
#       5: true,
#       6: true,
#       7: true,
#       8: true,
#       9: true,
#       10: true,
#       11: true,
#       12: false,
#       13: false,
#       14: false,
#       15: false,
#       16: false,
#       17: false,
#       18: false,
#       19: false,
#       20: false,
#       21: false,
#     },
#     6: {
#       3: true,
#       4: true,
#       5: true,
#       6: true,
#       7: true,
#       8: true,
#       9: true,
#       10: true,
#       11: true,
#       12: false,
#       13: false,
#       14: false,
#       15: false,
#       16: false,
#       17: false,
#       18: false,
#       19: false,
#       20: false,
#       21: false,
#     },
#     7: {
#       3: true,
#       4: true,
#       5: true,
#       6: true,
#       7: true,
#       8: true,
#       9: true,
#       10: true,
#       11: true,
#       12: true,
#       13: true,
#       14: true,
#       15: true,
#       16: true,
#       17: false,
#       18: false,
#       19: false,
#       20: false,
#       21: false,
#     },
#     8: {
#       3: true,
#       4: true,
#       5: true,
#       6: true,
#       7: true,
#       8: true,
#       9: true,
#       10: true,
#       11: true,
#       12: true,
#       13: true,
#       14: true,
#       15: true,
#       16: true,
#       17: false,
#       18: false,
#       19: false,
#       20: false,
#       21: false,
#     },
#     9: {
#       3: true,
#       4: true,
#       5: true,
#       6: true,
#       7: true,
#       8: true,
#       9: true,
#       10: true,
#       11: true,
#       12: true,
#       13: true,
#       14: true,
#       15: true,
#       16: true,
#       17: false,
#       18: false,
#       19: false,
#       20: false,
#       21: false,
#     },
#     10: {
#       3: true,
#       4: true,
#       5: true,
#       6: true,
#       7: true,
#       8: true,
#       9: true,
#       10: true,
#       11: true,
#       12: true,
#       13: true,
#       14: true,
#       15: true,
#       16: true,
#       17: false,
#       18: false,
#       19: false,
#       20: false,
#       21: false,
#     },
#     1: {
#       3: true,
#       4: true,
#       5: true,
#       6: true,
#       7: true,
#       8: true,
#       9: true,
#       10: true,
#       11: true,
#       12: true,
#       13: true,
#       14: true,
#       15: true,
#       16: true,
#       17: false,
#       18: false,
#       19: false,
#       20: false,
#       21: false,
#     },
#   }
#   return probabilities[dealerScore][playerScore];
# }
